CREATE TABLE "GCG_3898_Cust_Orders"(
 "INVOICE" CHAR(7),
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4),
 "CUSTOMER" CHAR(6),
 "PART" CHAR(20),
 "DESCRIPTION" CHAR(30),
 "QTY_SHIPPED" CHAR(50),
 "CUSTOMER_TYPE" CHAR(1));
